apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue" # below we created mongodb service with name mongodb so thats why we are using mongodb in the MONGO_URL here.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: ramcharankola2/catalogue:1.0.1
        imagePullPolicy: Always # safe to pull everytime, there may be changes in code and image with same version rebuilt and pushed, so safe to pull
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2 # how many failures to mark as unready
          periodSeconds: 10 # number of seconds between probes
          initialDelaySeconds: 15 # number of seconds to wait before starting the probe
          # successThreshold: 1 # number of successes to mark as ready
        livenessProbe:
          httpGet: # HTTP GET is used here because the application is exposing an HTTP endpoint
            path: /health
            port: 8080
          # tcpSocket:
          #   port: 8080 # TCP is used here because the application is listening on this port
          failureThreshold: 2 # how many failures to mark as unready
          periodSeconds: 10 # number of seconds between probes
          # initialDelaySeconds: 5 # number of seconds to wait before starting the probe
          # successThreshold: 1 # number of successes to mark as ready
        envFrom:
        - configMapRef:
            name: catalogue # reference to the configmap name defined above
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    project: roboshop
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP # TCP stands for transmission control protocol and UDP stands for user datagram protocol which is unreliable. TCP is reliable because it uses acknowledgment and it is connection oriented protocol.
    port: 8080 # service port
    targetPort: 8080 # container port